name: hexo build
on:
  push:
    branches:

      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: show path
      run: ls -l

    - name: build

      run: npm run build

   
